name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3

      - run: make install
      - run: go mod verify
      - run: go vet ./...

      - name: Run unit tests
        run: make test

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/TEST-*.xml"
        if: always()